### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tomoco-h** [tomoco-h/furima-39522#20]
いつもお世話になっております。
ようやくfurimaアプリが出来ました！大変お手数をおかけいたしますが、挙動確認をお願いいたします。

1.  フリマアプリのURL：https://furima-39522.onrender.com
2.  Basic認証
　　ID：admin、PW：2222
・出品者情報
　　mail：aaa@aaa.com、PW：a1a1a1a1a1
・購入者情報
　　mail：test@test.com、PW：aaa111

どうぞよろしくお願いいたします。

**Comment by snkw-works** [comment]
@tomoco-h さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### 商品出品機能
- [x] **入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
価格を入力しても、「販売手数料」「販売利益」が表示されない状態です。

#### 商品一覧表示機能
- [x] **商品出品時に登録した情報のうち、「画像・商品名・価格・配送料の負担」の4つの情報が、見本アプリと同様の形で表示されるよう修正しましょう**
「配送料の負担」が表示されていない状態です。

#### 商品購入機能
- [x] **エラーハンドリングの際、重複したエラーメッセージが表示されないよう修正しましょう**
「Post code can't be blank」「Phone can't be blank」が重複して表示されています。
<img width="874" alt="スクリーンショット 2023-12-03 11 30 02" src="https://github.com/tomoco-h/furima-39522/assets/54050089/8b81b875-f592-46ca-b662-e70ca31c5029">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！

修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tomoco-h** [comment]
ご指摘いただき、ありがとうございます。
修正をいたしましたので、再度ご確認いただけますと幸いです。
どうぞよろしくお願いいたします。

**Comment by mizuki-ueda** [comment]
@tomoco-h さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
